/**
 * The contract check (T-033) -- this file is the entire justification for a second scorer existing.
 *
 * D-011 forbids a second implementation of the scoring path. `score.ts` is one. What makes that
 * acceptable rather than a violation is that both implementations are held to a committed grid
 * generated by the Python one, and that the check runs **in the gate**: `npm test` is a step of the
 * `Frontend — Lint & Type Check` job, which is a required status check on `main`.
 *
 * Drift is caught from both directions and neither can be resolved locally:
 *
 *  - TypeScript drifts -> this file fails, the frontend job goes red.
 *  - Python drifts -> `backend/tests/test_contract.py` finds the committed file stale, the backend
 *    job goes red. Regenerating the file to fix that does not help TypeScript: the file can only
 *    ever encode what Python says, so a regenerated file still disagrees with a wrong scorer.
 *
 * Contributions are compared with `toBe` -- exact IEEE-754 equality, not a tolerance. Each is three
 * operations in a fixed order on doubles, which both languages perform identically; see
 * `score.ts`'s note on why the parenthesization is load-bearing. Only the probability, which passes
 * through `exp`, gets any slack.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { decompose, type Decomposition, type LinearModel } from "./score";

interface ContractCase {
  readonly id: string;
  readonly model: string;
  readonly features: Record<string, number>;
  readonly expected: {
    readonly home_win_probability: number;
    readonly baseline_logit: number;
    readonly logit: number;
    readonly contributions: Record<string, number>;
  };
}

interface ContractDocument {
  readonly contract_version: number;
  readonly probability_tolerance: number;
  readonly models: Record<string, Omit<LinearModel, "model_version">>;
  readonly cases: readonly ContractCase[];
}

/**
 * Read with `fs` rather than `import`. A 50 KB JSON import gives TypeScript a literal type with a
 * few thousand members to carry through every `tsc --noEmit`, for no benefit -- the shape is
 * declared above, and the runtime version check below is what actually guards it.
 */
const CONTRACT: ContractDocument = JSON.parse(
  readFileSync(path.join(__dirname, "contract-vectors.json"), "utf8"),
) as ContractDocument;

/** The shape this file knows how to read. A bump means the reader must be updated, not that the
 * cases changed -- refusing is how that stays true rather than silently reading `undefined`. */
const SUPPORTED_CONTRACT_VERSION = 1;

function modelFor(entry: ContractCase): LinearModel {
  const spec = CONTRACT.models[entry.model];
  if (!spec) {
    throw new Error(`case ${entry.id} names model ${entry.model}, which the document does not hold`);
  }
  return { model_version: `contract:${entry.model}`, ...spec };
}

/**
 * Every disagreement between a scorer and the committed grid.
 *
 * Returned rather than asserted so the same comparison can be pointed at a deliberately wrong
 * scorer -- see the non-vacuity test at the bottom. A check that has never been shown to fail is a
 * check nobody has any reason to believe.
 */
function disagreements(
  scorer: (model: LinearModel, features: Record<string, number>) => Decomposition,
): string[] {
  const out: string[] = [];
  for (const entry of CONTRACT.cases) {
    const actual = scorer(modelFor(entry), entry.features);
    const { expected } = entry;

    if (Math.abs(actual.homeWinProbability - expected.home_win_probability) > CONTRACT.probability_tolerance) {
      out.push(
        `${entry.id}: probability ${actual.homeWinProbability} vs ${expected.home_win_probability}`,
      );
    }
    if (actual.baselineLogit !== expected.baseline_logit) {
      out.push(`${entry.id}: baseline ${actual.baselineLogit} vs ${expected.baseline_logit}`);
    }
    if (actual.logit !== expected.logit) {
      out.push(`${entry.id}: logit ${actual.logit} vs ${expected.logit}`);
    }
    for (const [name, value] of Object.entries(expected.contributions)) {
      if (actual.contributions[name] !== value) {
        out.push(`${entry.id}: contribution ${name} ${actual.contributions[name]} vs ${value}`);
      }
    }
  }
  return out;
}

describe("the scoring contract", () => {
  it("reads a document version it understands", () => {
    expect(CONTRACT.contract_version).toBe(SUPPORTED_CONTRACT_VERSION);
  });

  it("has a grid worth agreeing on", () => {
    // A contract satisfied by three easy cases is not a contract. These floors are what stop the
    // grid being quietly narrowed until it passes.
    expect(CONTRACT.cases.length).toBeGreaterThanOrEqual(140);
    expect(Object.keys(CONTRACT.models).length).toBeGreaterThanOrEqual(6);

    const probabilities = CONTRACT.cases.map((c) => c.expected.home_win_probability);
    expect(Math.min(...probabilities)).toBeLessThan(1e-6);
    expect(Math.max(...probabilities)).toBeGreaterThan(1 - 1e-6);

    const contributions = CONTRACT.cases.flatMap((c) => Object.values(c.expected.contributions));
    expect(contributions.some((v) => v > 0)).toBe(true);
    expect(contributions.some((v) => v < 0)).toBe(true);
  });

  it("agrees with the Python implementation on every case", () => {
    expect(disagreements(decompose)).toEqual([]);
  });

  it("would notice a scorer that dropped the intercept", () => {
    // Non-vacuity. The mutation is chosen to be invisible in the *contributions* and wrong only in
    // the probability and the logit -- so this also proves those two comparisons carry weight,
    // rather than the contribution loop doing all the work.
    const withoutIntercept = (model: LinearModel, features: Record<string, number>) => {
      const real = decompose(model, features);
      return { ...real, baselineLogit: 0, logit: real.logit - model.intercept };
    };
    expect(disagreements(withoutIntercept).length).toBeGreaterThan(0);
  });

  it("would notice a scorer that skipped standardization", () => {
    const unstandardized = (model: LinearModel, features: Record<string, number>) => {
      const contributions: Record<string, number> = {};
      let total = 0;
      for (const name of model.feature_names) {
        const c = model.coefficients[name] * features[name];
        contributions[name] = c;
        total += c;
      }
      const logit = model.intercept + total;
      return {
        homeWinProbability: 1 / (1 + Math.exp(-logit)),
        baselineLogit: model.intercept,
        logit,
        contributions,
      };
    };
    expect(disagreements(unstandardized).length).toBeGreaterThan(0);
  });

  it("would notice a scorer that summed the terms in the wrong order", () => {
    // The subtlest mutation available, and the one exact equality exists for: floating-point
    // addition is not associative, so reversing the order changes the last ulp of the logit while
    // every individual contribution stays bit-identical. A comparison with any tolerance at all
    // would find nothing here.
    //
    // The mutation changes the summation order and *only* that -- the probability is recomputed
    // with the same stable sigmoid the real scorer uses. An earlier version used the naive
    // `1/(1+exp(-z))`, which differs from the stable form on large negative logits, so it was
    // partly detecting the wrong thing.
    const stableSigmoid = (z: number) => {
      if (z >= 0) return 1 / (1 + Math.exp(-z));
      const e = Math.exp(z);
      return e / (1 + e);
    };
    const reversed = (model: LinearModel, features: Record<string, number>) => {
      const real = decompose(model, features);
      let total = 0;
      for (const name of [...model.feature_names].reverse()) {
        total += real.contributions[name];
      }
      const logit = model.intercept + total;
      return { ...real, logit, homeWinProbability: stableSigmoid(logit) };
    };
    expect(disagreements(reversed).length).toBeGreaterThan(0);
  });
});
