/**
 * The browser's scorer (T-033) -- a second implementation of `backend/model/prediction.decompose`.
 *
 * ## D-011 forbids this, and the contract check is the entire justification
 *
 * D-011's mechanism is that training and inference call one feature function, so there is no second
 * implementation to drift from. This file is a second implementation. It exists because T-034's
 * what-if panel must run in the browser: story 25 wants a visitor to move a value and watch the
 * probability respond, and story 27 requires that exploration never reach anything that records it.
 * A round trip per slider drag would be slow *and* a write-shaped path into a service whose whole
 * security property is that it has none.
 *
 * What is duplicated is kept as small as it can be: the logistic arithmetic, and nothing else.
 * **This module does not compute features.** `compute_features` stays a single implementation behind
 * its property test, and what arrives here is a feature vector the API already produced, with one or
 * two values changed by the visitor. A what-if changes a feature's *value*, never the history it was
 * computed from -- a panel that recomputed `elo_diff` from game results in the browser would be
 * exactly the drift this design avoids.
 *
 * `contract.test.ts` scores a committed grid generated by the Python implementation and asserts
 * agreement -- exactly on every contribution, and to a pinned tolerance on the probability. It runs
 * in the frontend CI job, which is a required check on `main`.
 *
 * ## Why the arithmetic is written the way it is
 *
 * Two details are load-bearing rather than stylistic, and both exist so the contract can hold this
 * to *exact* equality on contributions instead of a tolerance:
 *
 *  1. `coefficient * ((value - mean) / std)` -- three IEEE-754 operations in a fixed order. Both
 *     languages perform them identically on doubles. Rewriting as `c * (v - m) / s` reassociates
 *     the rounding and quietly breaks agreement in the last ulp.
 *  2. Terms are summed in `feature_names` order, starting from 0, then the intercept is added --
 *     mirroring Python's `intercept + sum(contributions.values())`, where dict order is insertion
 *     order. Floating-point addition is not associative, so summation order is part of the answer.
 *
 * The probability is the one value that passes through `exp`, which is the platform's and may
 * differ in the last ulp. That is the only number the contract gives any slack.
 */

/** A fitted linear model, in the shape `GET /predictions/model` returns. */
export interface LinearModel {
  readonly model_version: string;
  readonly feature_names: readonly string[];
  readonly intercept: number;
  readonly coefficients: Readonly<Record<string, number>>;
  readonly means: Readonly<Record<string, number>>;
  readonly stds: Readonly<Record<string, number>>;
}

/**
 * A probability and the terms that produced it.
 *
 * Deliberately carries no game id and no moment. This is what a what-if produces -- a probability
 * for a vector nobody predicted -- and a type with nowhere to put a game id is a type that cannot
 * be mistaken for a prediction (story 27).
 */
export interface Decomposition {
  readonly homeWinProbability: number;
  readonly baselineLogit: number;
  /** Equal to `baselineLogit + sum(contributions)` by construction. */
  readonly logit: number;
  /** Per-feature contributions **in log-odds**, not probability. +0.5 is not "+50%". */
  readonly contributions: Readonly<Record<string, number>>;
}

export class ScoringError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ScoringError";
  }
}

function requireFinite(value: unknown, what: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new ScoringError(`${what} must be a finite number, got ${JSON.stringify(value)}`);
  }
  return value;
}

/**
 * Numerically stable logistic, mirroring `prediction._sigmoid` branch for branch.
 *
 * The naive `1 / (1 + exp(-z))` overflows to `Infinity` for large negative `z` and returns 0 where
 * it should return a small positive number. Both branches are exercised by the contract grid, which
 * spans probabilities from 1.4e-21 to exactly 1.
 */
function sigmoid(z: number): number {
  if (z >= 0) {
    return 1 / (1 + Math.exp(-z));
  }
  const expZ = Math.exp(z);
  return expZ / (1 + expZ);
}

/**
 * Validate a model as it arrives from the network.
 *
 * Not defensive padding: this is a boundary. The model reaches the browser as JSON over HTTP, so
 * "the response was an error page" and "a std came back as zero" are things that happen, and a
 * `std` of 0 would produce `Infinity` contributions in JavaScript where Python raises. Refusing
 * here is what stops that difference ever mattering.
 */
export function assertUsableModel(model: LinearModel): void {
  if (!Array.isArray(model.feature_names) || model.feature_names.length === 0) {
    throw new ScoringError("model has no feature_names");
  }
  requireFinite(model.intercept, "intercept");
  for (const name of model.feature_names) {
    requireFinite(model.coefficients[name], `coefficient for ${name}`);
    requireFinite(model.means[name], `mean for ${name}`);
    const std = requireFinite(model.stds[name], `std for ${name}`);
    if (std <= 0) {
      throw new ScoringError(
        `std for ${name} is ${std}; standardization by a non-positive std is not defined ` +
          "(the fitter substitutes 1.0 for a degenerate feature, so this means the model is wrong)",
      );
    }
  }
}

/**
 * **The arithmetic.** Probability and per-feature contributions for one feature vector.
 *
 * Refuses a missing or unexpected feature rather than filling a default, mirroring `to_vector`: a
 * silently-zero feature shows up as a mildly disappointing number and nothing else.
 */
export function decompose(
  model: LinearModel,
  features: Readonly<Record<string, number>>,
): Decomposition {
  assertUsableModel(model);

  const missing = model.feature_names.filter((name) => !(name in features));
  const unexpected = Object.keys(features).filter((name) => !model.feature_names.includes(name));
  if (missing.length > 0 || unexpected.length > 0) {
    throw new ScoringError(
      `feature vector does not match the model (missing=[${missing}], unexpected=[${unexpected}])`,
    );
  }

  const contributions: Record<string, number> = {};
  let total = 0;
  for (const name of model.feature_names) {
    const value = requireFinite(features[name], `feature ${name}`);
    // Three operations, this order. See the module docstring.
    const contribution = model.coefficients[name] * ((value - model.means[name]) / model.stds[name]);
    contributions[name] = contribution;
    total += contribution;
  }

  const logit = model.intercept + total;
  return {
    homeWinProbability: sigmoid(logit),
    baselineLogit: model.intercept,
    logit,
    contributions,
  };
}

/**
 * A hypothetical vector: the real one with some values replaced.
 *
 * Exists so a caller cannot accidentally mutate the prediction's own feature object -- the fence
 * between real and hypothetical (story 26) is easier to hold in the UI when the data structures
 * behind it were never shared in the first place.
 */
export function withValues(
  features: Readonly<Record<string, number>>,
  changes: Readonly<Record<string, number>>,
): Record<string, number> {
  const next = { ...features };
  for (const [name, value] of Object.entries(changes)) {
    if (!(name in features)) {
      throw new ScoringError(`cannot change ${name}: it is not one of this prediction's features`);
    }
    next[name] = requireFinite(value, `value for ${name}`);
  }
  return next;
}
